version: "2"
services:
  base:
    image: node:12
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/

  install:
    extends:
      service: base
    command: npm i

  dev:
    extends:
      service: base
    command: npm run dev
    environment:
      - SERVER_PORT=$SERVER_PORT
      - APP_PORT=$APP_PORT
      - APP_PORT_HMR=$APP_PORT_HMR
    ports:
      - $APP_PORT:$APP_PORT
      - $APP_PORT_HMR:$APP_PORT_HMR
      - $SERVER_PORT:$SERVER_PORT

  dev-server:
    extends:
      service: base
    command: npm run dev-server
    environment:
      - SERVER_PORT=$SERVER_PORT
    ports:
      - $SERVER_PORT:$SERVER_PORT

  dev-app:
    extends:
      service: base
    command: npm run dev-app
    environment:
      - APP_PORT=$APP_PORT
      - APP_PORT_HMR=$APP_PORT_HMR
    ports:
      - $APP_PORT:$APP_PORT
      - $APP_PORT_HMR:$APP_PORT_HMR

  server:
    extends:
      service: dev-server
    command: npm run server
    environment:
      - SERVER_PORT=$SERVER_PORT

  app:
    extends:
      service: dev-app
    command: npm run app

  build:
    extends:
      service: base
    command: npm run build
