version: "2"
services:
  base:
    image: node:12
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/

  install:
    extends:
      service: base
    command: npm i

  dev:
    extends:
      service: base
    command: npm run dev
    ports:
      - 1234:1234
      - 1235:1235
      - 3000:3000

  dev-server:
    extends:
      service: base
    command: npm run dev-server
    ports:
      - 3000:3000

  dev-app:
    extends:
      service: base
    command: npm run dev-app
    ports:
      - 1234:1234
      - 1235:1235

  server:
    extends:
      service: base
    command: npm run server
    ports:
      - 3000:3000

  build:
    extends:
      service: base
    command: npm run build
