version: '2'
services:

  base:
    image: node:12
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/

  install:
    extends:
      service: base
    command: npm i

  server:
    extends:
       service: base
    command: npm run server
    ports:
      - 3000:3000