version: '2'
services:

  base:
    image: node:12
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/

  install:
    extends:
      service: base
    command: npm i

  dev:
    extends:
      service: base
    command: npm run dev
    # command: tail -f /dev/null
    ports:
      - 1234:1234 # app
      - 1235:1235 # app hot reload
      - 3000:3000 # rml mapper server

  # dev:
  #   image: node:12
  #   volumes:
  #     - .:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: npm run dev
  #   ports:
  #     - 1234:1234 # app
  #     - 1235:1235 # app hot reload
  #     - 3000:3000 # rml mapper server

  # app:
  #   image: node:12
  #   volumes:
  #     - ./:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: npm run dev-app
  #   ports:
  #     - 1234:1234
  #     - 1235:1235

  # server:
  #   image: node:12
  #   volumes:
  #     - ./:/usr/src/app
  #   working_dir: /usr/src/app
  #   command: npm run dev-server
  #   ports:
  #     - 3000:3000